### PR TITLE
HTML&CSS3 - Embedding Images and Video - complete project

### PR DESCRIPTION
**Pull request by canriquez**
Hello, please review this project.
Working team: @canriquez and @fivan18

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello @canriquez  @fivan18 , 👋 There some issues below need to be fixed. 

- [ ] It shows the recommended video's thumbnail preview (embed some image there)
- [ ] Write a descriptive readme (decription, technology used, author, demo link)

----
### Don't forgot to request for another code review
----

**Pon Muthu Selvam N**
_If you have any queries, feel free to ping me on slack_

**Comment by canriquez** [comment]
> # Changes required 🛑
> ### Hello @canriquez @fivan18 , 👋 There some issues below need to be fixed.
> * [ ]  It shows the recommended video's thumbnail preview (embed some image there)
> * [ ]  Write a descriptive readme (decription, technology used, author, demo link)
> 
> ### Don't forgot to request for another code review
> **Pon Muthu Selvam N**
> _If you have any queries, feel free to ping me on slack_

Hi, and thanks for your review. I am a little confused about your first change requirement. 
- We do have embedded images for the video recommendation. You mean to change them in any way?.
- I have now updated the readme file with your comments.  I just created a new code review.
thanks for your help.

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello @canriquez  @fivan18 , 👋 There is a issue below need to be fixed. 

- [ ] check the image link in the video recommendation, I think it is broken because I can't see those.

----
### Don't forgot to request for another code review
----

**Pon Muthu Selvam N**
_If you have any queries, feel free to ping me on slack_

**Comment by fivan18** [comment]
@imhta please check the development branch

**Comment by fivan18** [comment]
@imhta thanks.  We changed the link of the images of the thumbnail videos.

**Comment by mosesogwo** [comment]
Good job @fivan18 , @canriquez. :+1: 

You have effected the requested changes appropriately.

Good luck in your next project.

**Status: Approved!**

**Pull request merged**
